apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort

# ---
# # Service interne
# apiVersion: v1
# kind: Service
# metadata:
#   name: app2-clusterip
# spec:
#   selector:
#     app: app2
#   ports:
#     - port: 80 # le port “virtuel” du service à l’intérieur du cluster
#       targetPort: 80 # le port du pod que le service expose
#   type: ClusterIP