Vagrant.configure("2") do |config|

  config.vm.define "hrischmaS" do |server|
    # Box légère, minimal (pas de desktop), provider libvirt/KVM
    server.vm.box = "generic/debian12"
    server.vm.hostname = "hrischmaS"
    server.vm.boot_timeout = 600
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.network :forwarded_port, guest: 22, host: "8082", id: "ssh"
    server.vm.synced_folder "./apps", "/apps", type: "nfs", nfs_udp: false
    server.vm.synced_folder "./ingress", "/ingress", type: "nfs", nfs_udp: false

    server.vm.provider :libvirt do |lv|
      lv.memory = 1024
      lv.cpus = 2
      lv.cpu_mode = "host-passthrough"
    end

    server.vm.provision "shell", path: "./server.sh"
  end
end
