Vagrant.configure("2") do |config|

    config.vm.define "malangloS" do |server|
      server.vm.box = "hashicorp/bionic64"
      server.vm.hostname = "malangloS"
      server.vm.network :private_network, ip: "192.168.56.110"
      server.vm.network "forwarded_port", guest: 22, host: "8082", id: "ssh"

      server.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
      end

      server.vm.provision "shell", path: "server.sh"

      # # Provisioning shell pour installer k3s
      # server.vm.provision "shell", inline: <<-SHELL
      #   curl -sfL https://get.k3s.io | sh -
      # SHELL

      # # Provisioning shell pour déployer tes apps
      # server.vm.provision "shell", inline: <<-SHELL
      #   export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      #   kubectl apply -f /vagrant/apps.yaml
      # SHELL
    end
 
end
