apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitlab.gitlab.svc.cluster.local/root/iot-bonus.git
  username: root
  password: glpat-setup-token-42
  insecure: "true"
